### PR TITLE
Add Support for 1.20/1.20.1

### PR DESCRIPTION
**Pull request by ghost**
Yo man, here, have some code to allow 1.20 Fabric Servers to use your mod. I know the Merge says 1.19, but there is no 1.20 Branch that I can commit to, lmk if I should make another pull Request or something, have fun!

### CODE REVIEW

**Comment by tuxinal** [comment]
Thank you! i will make a new branch and switch it to that

**Comment by ghost** [comment]
You're welcome!

**Comment by tuxinal** [comment]
it took me a bit to test sorry about that. i'll merge this tomorrow.
btw do you mind if i add you to the authors instead of your description changes?

**Comment by ghost** [comment]
I don't mind you changing it, don't worry! Feel free to modify it at your will.
EDIT: Oh yeah, I almost forgot, you can save yourself some trouble and use the [Carpet Mod](https://github.com/gnembon/fabric-carpet)'s /player command to test Deaths.

**Pull request merged**
